{
 "title": "k6_DPU_zif_events",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Transaction Response Time - Summary Transactions / second",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "metric without cache (first event)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "group::tag" ], "type": "tag" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT mean(\"startedT\")  / 100, mean(\"endedT\"), mean(\"maxAT\"), mean(\"meanAT\"), mean(\"minAT\") FROM \"undefined\".\"jmeter\" WHERE (\"transaction\"::tag = 'internal') AND $timeFilter GROUP BY time(10s), \"endedT\"::field, \"startedT\"::field, \"maxAT\"::field, \"minAT\"::field, \"meanAT\"::field fill(null)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "=", "value": "::kafka_no_cash_event_first" }
     ]
    },
    {
     "alias": "metric with cache",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "group::tag" ], "type": "tag" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT mean(\"startedT\")  / 100, mean(\"endedT\"), mean(\"maxAT\"), mean(\"meanAT\"), mean(\"minAT\") FROM \"undefined\".\"jmeter\" WHERE (\"transaction\"::tag = 'internal') AND $timeFilter GROUP BY time(10s), \"endedT\"::field, \"startedT\"::field, \"maxAT\"::field, \"minAT\"::field, \"meanAT\"::field fill(null)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "=", "value": "::kafka_with_cash_event" }
     ]
    },
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"k6_group_duration\" WHERE (\"group\"::tag = '::kafka_no_cash_event') AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "=", "value": "::kafka_main_load" },
      { "condition": "OR", "key": "group::tag", "operator": "=", "value": "::kafka_no_cash_event_first" },
      { "condition": "OR", "key": "group::tag", "operator": "=", "value": "::fast_produce_kafka" }
     ]
    }
   ]
  },
  {
   "title": "Transactions by scenarios",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Main load with cache transactions",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"k6_group_duration\" WHERE (\"group\"::tag = '::kafka_no_cash_event') AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "=", "value": "::kafka_main_load" }
     ]
    },
    {
     "alias": "Transactions metrics with cache",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"k6_group_duration\" WHERE (\"group\"::tag = '::kafka_no_cash_event') AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "group::tag", "operator": "=", "value": "::kafka_with_cash_event" }
     ]
    },
    {
     "alias": "Transactions metrics without cache (first event)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"k6_group_duration\" WHERE (\"group\"::tag = '::kafka_no_cash_event') AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "=", "value": "::kafka_no_cash_event_first" }
     ]
    },
    {
     "alias": "Transaction amount (TPS)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"k6_group_duration\" WHERE (\"group\"::tag = '::kafka_no_cash_event') AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "=", "value": "::kafka_main_load" },
      { "condition": "OR", "key": "group::tag", "operator": "=", "value": "::kafka_no_cash_event_first" },
      { "condition": "OR", "key": "group::tag", "operator": "=", "value": "::fast_produce_kafka" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "group::tag" ], "type": "tag" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT mean(\"startedT\")  / 100, mean(\"endedT\"), mean(\"maxAT\"), mean(\"meanAT\"), mean(\"minAT\") FROM \"undefined\".\"jmeter\" WHERE (\"transaction\"::tag = 'internal') AND $timeFilter GROUP BY time(10s), \"endedT\"::field, \"startedT\"::field, \"maxAT\"::field, \"minAT\"::field, \"meanAT\"::field fill(null)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "!=", "value": "::pacing_group" },
      { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT sum(\"count\")  / 10 FROM \"autogen\".\"k6_group_duration\" WHERE (\"group\"::tag = '::kafka_main_load' OR \"group\"::tag = '::kafka_no_cash_event_first' OR \"group\"::tag = '::fast_produce_kafka') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "=", "value": "::kafka_main_load" }
     ]
    }
   ]
  },
  {
   "title": "Internal  telegraf metrics",
   "type": "timeseries",
   "description": "buffer_limit - предельный размер буфера\nbuffer_size - размер занятого буфера\nmetrics_dropped - должны быть по-нулям",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "buffer_limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "query": "SELECT mean(*) FROM \"autogen\".\"internal_write\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "buffer_limit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "buffer_size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "query": "SELECT mean(*) FROM \"autogen\".\"internal_write\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "buffer_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "metrics_dropped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "query": "SELECT mean(*) FROM \"autogen\".\"internal_write\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "metrics_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Response Time - Summary Transactions / second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "group::tag" ], "type": "tag" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT mean(\"startedT\")  / 100, mean(\"endedT\"), mean(\"maxAT\"), mean(\"meanAT\"), mean(\"minAT\") FROM \"undefined\".\"jmeter\" WHERE (\"transaction\"::tag = 'internal') AND $timeFilter GROUP BY time(10s), \"endedT\"::field, \"startedT\"::field, \"maxAT\"::field, \"minAT\"::field, \"meanAT\"::field fill(null)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "!=", "value": "::pacing_group" }
     ]
    },
    {
     "alias": "tps",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "k6_iterations",
     "query": "SELECT mean(\"startedT\")  / 100, mean(\"endedT\"), mean(\"maxAT\"), mean(\"meanAT\"), mean(\"minAT\") FROM \"undefined\".\"jmeter\" WHERE (\"transaction\"::tag = 'internal') AND $timeFilter GROUP BY time(10s), \"endedT\"::field, \"startedT\"::field, \"maxAT\"::field, \"minAT\"::field, \"meanAT\"::field fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "k6_group_duration",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"k6_group_duration\" WHERE (\"group\"::tag = '::kafka_no_cash_event') AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "=", "value": "::kafka_main_load" },
      { "condition": "OR", "key": "group::tag", "operator": "=", "value": "::kafka_no_cash_event_first" },
      { "condition": "OR", "key": "group::tag", "operator": "=", "value": "::fast_produce_kafka" }
     ]
    }
   ]
  },
  {
   "title": "All request responses time - Running Vusers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "vu",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "k6_vus",
     "query": "SELECT mean(\"startedT\")  / 100, mean(\"endedT\"), mean(\"maxAT\"), mean(\"meanAT\"), mean(\"minAT\") FROM \"undefined\".\"jmeter\" WHERE (\"transaction\"::tag = 'internal') AND $timeFilter GROUP BY time(10s), \"endedT\"::field, \"startedT\"::field, \"maxAT\"::field, \"minAT\"::field, \"meanAT\"::field fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "VU",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "vus",
     "query": "SELECT mean(\"startedT\")  / 100, mean(\"endedT\"), mean(\"maxAT\"), mean(\"meanAT\"), mean(\"minAT\") FROM \"undefined\".\"jmeter\" WHERE (\"transaction\"::tag = 'internal') AND $timeFilter GROUP BY time(10s), \"endedT\"::field, \"startedT\"::field, \"maxAT\"::field, \"minAT\"::field, \"meanAT\"::field fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}